spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  # this is to add external configurations
  application:
    name:
      cards
  profiles:
    active: prod


server:
  port: 8087



