version: "3.8"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - eazybank

  configserver:
    container_name: configserver
    image: ishuthakur/configserver:latest
#    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - eazybank
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eurekaserver:
    image: ishuthakur/eurekaserver:latest
#    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - eazybank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8081/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  accounts:
    image: ishuthakur/accounts:latest
#    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - eazybank
    depends_on:
      - configserver
      - eurekaserver
    deploy:                     # this is for accounts
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8081/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  loans:
    image: ishuthakur/loans:latest
#    mem_limit: 700m
    ports:
      - "8002:8002"
    networks:
      - eazybank
    depends_on:
      - configserver
      - eurekaserver
    deploy:                     # this is for accounts
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8081/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  eazybank:                  